---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
  - name: Update local host file
    lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='127.0.0.1 {{item}}' state=present
    with_items:
      - graphite.local
      - sentry.local
