#!/bin/bash
SESSION=$USER

tmux -2 new-session -d -s $SESSION

function configure () {
  tmux send-keys "vagrant ssh" C-m
  tmux send-keys "cd /opt/dev/koomus" C-m
  tmux send-keys "clear" C-m

if [ ! -z "$1" ]
   then
     tmux send-keys "$1" C-m
   fi
}

# Setup main window for VIM
tmux new-window -t $SESSION:1 -n 'Dev'
tmux split-window -h
tmux select-pane -t 0
tmux resize-pane -R 10
configure 'vim'

# Setup top left window for REPL
tmux select-pane -t 1
configure 'lein repl'

# Setup bottom right window as shell - e.g. for git
tmux split-window -v
tmux select-pane -t 2
configure

# Attach to session
tmux -2 attach-session -t $SESSION
