---
# SETUP FIREWALL
# ====================================================

- name: Wait for server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
  sudo: false

- name: Install fail2ban
  action: apt pkg=fail2ban state=installed

- name: Setup ufw
  action: shell ufw allow 22
  
- name: Setup ufw
  action: shell ufw allow 80
  
- name: Setup ufw
  action: shell ufw allow 443

- name: Setup ufw
  action: shell ufw allow 5017  

- name: Setup ufw
  action: shell ufw allow 1236  

- name: Setup ufw
  action: shell ufw allow 8989  

- name: Enable ufw
  action: shell echo 'y' | ufw enable
  
