---
- hosts: all
  sudo: yes
  gather_facts: no
  vars:
    redis_conf_path: /etc/redis/
    install_path: /usr/local/bin/lein # system wide install
    lein_script_path: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  roles:
    - firewall
    - clojure
    - dev-tools
    - redis

- hosts: all
  sudo: no
  gather_facts: no
  vars:
    git_user: "{{ lookup('pipe','git config --get user.name') }}"
    git_email: "{{ lookup('pipe','git config --get user.email') }}"
    git_editor: vim
  roles:
    - dev-shell

# monitoring
- hosts: all
  sudo: yes
  vars:
    graphite:
      version: master
      timezone: Europe/Paris
      workers: 4
      host: 0.0.0.0
      server: graphite.local
      secret_key: 'ob3sow^ik#4q(k5*tgw&6j+osyr^@0jus$yd+-#^&^d#%yim1!'
    carbon:
      host: 0.0.0.0
      ssl: no
    db_graphite:
      name: graphite
      user: graphite
      password: graphite
    sentry:
      server: sentry.local
      url: http://sentry.local
      secret_key: 'my69eAMYjzqtmfaRJ107MeXCYDTaxQdNZPr8YOe/zOV5pIUoZa5biA=='
    db_sentry:
      name: sentry
      user: sentry
      password: sentry
    superuser_sentry:
      username: admin
      email: admin@example.com
      password: admin
  roles:
    - monitoring/common
    - monitoring/python
    - monitoring/supervisor
    - role: monitoring/nginx
      nginx_sites: none
    - monitoring/postgres
    - monitoring/graphite
    - monitoring/nodejs
    - monitoring/statsd
    - monitoring/sentry
