---
# SETUP DEV TOOLS
# ====================================================

- name: install git
  apt: pkg=git state=installed

- name: install nerdtree
  git: repo=https://github.com/scrooloose/nerdtree.git dest=/home/vagrant/.vim/bundle/nerdtree

- name: install vim-fireplace
  git: repo=https://github.com/tpope/vim-fireplace.git dest=/home/vagrant/.vim/bundle/vim-fireplace

- name: install vim-classpath
  git:  repo=https://github.com/tpope/vim-classpath.git dest=/home/vagrant/.vim/bundle/vim-classpath

- name: install vim-clojure-static
  git: repo=https://github.com/guns/vim-clojure-static.git dest=/home/vagrant/.vim/bundle/vim-clojure-static

- name: install paredit
  git: repo=https://github.com/vim-scripts/paredit.vim.git dest=/home/vagrant/.vim/bundle/paredit.vim

- name: install rainbow-parenthesis
  git: repo=https://github.com/kien/rainbow_parentheses.vim.git dest=/home/vagrant/.vim/bundle/rainbow_parenthesis.vim

- name: install airline
  git: repo=https://github.com/bling/vim-airline dest=/home/vagrant/.vim/bundle/vim-airline

- name: install signify
  git: repo=https://github.com/mhinz/vim-signify dest=/home/vagrant/.vim/bundle/vim-signify

- name: install gitgutter
  git: repo=https://github.com/airblade/vim-gitgutter.git dest=/home/vagrant/.vim/bundle/vim-gitgutter

- name: install tmuxline
  git: repo=https://github.com/edkolev/tmuxline.vim dest=/home/vagrant/.vim/bundle/tmuxline 

- name: install mustang vim
  git: repo=https://github.com/croaker/mustang-vim.git dest=/home/vagrant/.vim/bundle/mustang-vim

- name: tmux dev script | add to bin
  copy: src=koomus dest=/usr/local/bin/koomus

- name: tmux dev script | make executable
  command: chmod 755 /usr/local/bin/koomus
